# -*- coding: utf-8 -*-
"""change dataframe column name.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3tP686dcAzDYEyBRM4DnWySv1AOKj1d
"""

#changing dataframe column name

import pandas as pd

df =pd.DataFrame({'col one':[100,200],'col two':[300,400]})
df

#rename korar first way

df = df.rename({'col one':'Colum_One'},axis='columns')
df

#second column

df= df.rename({'col two':'Colum_Two'},axis = 'columns')
df

#2nd way of renaming the column

import pandas as pd

df =pd.DataFrame({'col one':[100,200],'col two':[300,400]})
df

df.columns = ['Column_1','Column_2']


df

#3rd way of renaming of a column


import pandas as pd

df =pd.DataFrame({'col one':[100,200],'col two':[300,400]})
df

df.columns=df.columns.str.replace(' ','_')
df