# -*- coding: utf-8 -*-
"""DataFrame and Read a CSV file using Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WkIZi3TjSRjeX-kjt6oZpRyIrvz365i
"""

#file upload command in Google Colab

from google.colab import files
uploaded = files.upload()

#read_csv()

import pandas as pd

df = pd.read_csv('ecommerce_customer_churn_data.csv')
#print(df)

print(df.head(3))