# -*- coding: utf-8 -*-
"""Unique , nunique, value_counts,count ,apply.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nh--TuKhwgT-sHmrOY2D9M9mBxRleMPT
"""

import pandas as pd
data ={
    'Store':['Walmart','Walmart','Costco','Costco','Target','Target'],
    'Customer':['Tim','Jerri','Mark','Denice','Ray','Sam'],
    'Sales':[150,200,550,90,430,120]
}
df=pd.DataFrame(data)
df
print(df)
df.groupby('Store')[['Sales']].sum()
df.groupby('Store').count()
df.groupby(['Store','Customer'])[['Sales']].count() # group by with multiple column

df.groupby('Store').count()[['Customer']] # kon store a customer koto jon