# -*- coding: utf-8 -*-
"""Import file to the Google Colab and read excel file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WkIZi3TjSRjeX-kjt6oZpRyIrvz365i
"""

#file upload command in Google Colab

from google.colab import files
uploaded = files.upload()

#df.read_excel() command

import pandas as pd

df = pd.read_excel('Challenge 1.xlsx')

df
#print(df)

