# -*- coding: utf-8 -*-
"""Row and Column opposite making.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0NqVHIvM-9L6-k6nNXIqNPhi33nLTfq
"""

import pandas as pd

student_data ={
    'Name':['Khalid','Ahmed','Ahsan'],
    'ID':[8,9,10],
    'Department':['CSE','IT','EEE'],
    'Age':[21,22,23]
}
df=pd.DataFrame(student_data)
print(df)
df


#row distribution in opposite order
df.loc[::-1] #this command is use to make this temporary

#df = df.loc[::-1].reset_index(drop = True) #use to make this permanently
#df

import pandas as pd

student_data ={
    'Name':['Khalid','Ahmed','Ahsan'],
    'ID':[8,9,10],
    'Department':['CSE','IT','EEE'],
    'Age':[21,22,23]
}
df=pd.DataFrame(student_data)
print(df)


df = df.loc[:,::-1] #use to change column
df