# -*- coding: utf-8 -*-
"""single data and multiple data remove using condition in Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xl100k95b-rRy3sH5tC_mPD45mp72-pz
"""

import pandas as pd

climate_data ={
    'Day' :['01.01.2023','02.01.2023','03.01.2023'],
    'Temperature':[31,27,30],
    'Windspeed' :[3,6,9],
    'event':['Sunny','Rainy','Cloudy']
}

df=pd.DataFrame(climate_data)
#print(df)
df

#test purpose a ekta column nilamm , jate important jinish drop kore abar kosto kora na lage

df['Newcolumn'] ='test'
df

#drop command using 1 condition

df.drop('Newcolumn',axis =1) #this is use for temporary delete

#to delete a column permanently we have to use

df.drop('Newcolumn',axis =1,inplace=True)
df

import pandas as pd

climate_data ={
    'Day' :['01.01.2023','02.01.2023','03.01.2023'],
    'Temperature':[31,27,30],
    'Windspeed' :[3,6,9],
    'event':['Sunny','Rainy','Cloudy']
}
df = pd.DataFrame(climate_data)
df

#[index based column drop system temporary]
df.drop(columns =df.columns[2])

#to delete a columns permanenetly form you dataframe use inplace = True

df.drop(index = df[df['event']=='Rainy'].index,inplace=True) #permanent ly delete command
df