# -*- coding: utf-8 -*-
"""Unique , nunique, value_counts,count ,apply.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nh--TuKhwgT-sHmrOY2D9M9mBxRleMPT
"""

import pandas as pd

data_dic={
    'col_1':[1,2,3,4,1],
    'col_2':['a','b','c','d','b'],
    'col_3':[1.1,2.2,3.3,4.4,4.4]
}
df = pd.DataFrame(data_dic)
df['col_2'].unique() #to find out all the unique value
df['col_2'].nunique() #to find how many unique value is present in this column

df['col_2'].value_counts() #how many times a value is occured

df['col_2'].count() #to see a value how many item in a column

def square(value):
  return value * value

df['col_1'].apply(square)

#df['col_4']=(df['col_1']*df['col_3']) #calcculative column
df

