# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5BGIu6fha8HHXg8UOLVy3qHzpMMY__r
"""

import pandas as pd
student_data= {
    'Name' : ['Khalid','Rahim','Karim','Akash'],
    'Stu_ID' : [1,2,3,4],
    'Department' : ['CSE','EEE','CSE','CSE'],
    'CGPA' : [3.80,3.50,3.22,2.90]
}

df = pd.DataFrame(student_data)
#df
#print(df)

df.info()

#use of df.describe() to find out the mean, std,min

import pandas as pd
student_data= {
    'Name' : ['Khalid','Rahim','Karim','Akash'],
    'Stu_ID' : [1,2,3,4],
    'Department' : ['CSE','EEE','CSE','CSE'],
    'CGPA' : [3.80,3.50,3.22,2.90]
}

df = pd.DataFrame(student_data)
df

df.describe()
#df.describe(include ='all')

#existing table a new column and new calculative column nicchi

import pandas as pd
student_data= {
    'Name' : ['Khalid','Rahim','Karim','Akash'],
    'Age' : [19,20,30,40],
    'Department' : ['CSE','EEE','CSE','CSE'],
    'CGPA' : [3.80,3.50,3.22,2.90],
    'Course_credit':[3,4,5,6]
}

df = pd.DataFrame(student_data)
df

#taking new column in a existing table

df['Newcolumn']='Test'
df

#taking new column and operation

df['A*C'] = df['Age'] * df['Course_credit']
df

#taking new column and multiple operation

df['Age * course er percentage'] = df['Age'] * df['Course_credit'] / 100
df

import pandas as pd
student_data= {
    'Name' : ['Khalid','Rahim','Karim','Akash'],
    'Age' : [19,20,30,40],
    'Department' : ['CSE','EEE','CSE','CSE'],
    'CGPA' : [3.80,3.50,3.22,2.90],
    'Course_credit':[3,4,5,6]
}

df = pd.DataFrame(student_data)
df

#addition operation with a column

df['Age'] = df['Age'] + 5
df

#update a column

df['Age']=[40,50,60,70]
df

import pandas as pd

climate_data ={
    'Day' :['01.01.2023','02.01.2023','03.01.2023'],
    'Temperature':[31,27,30],
    'Windspeed' :[3,6,9],
    'event':['Sunny','Rainy','Cloudy']
}

df = pd.DataFrame(climate_data)
df

#single dataframe update using single condition condition

df.at[2,'Temperature']=40
df
df.at[1,'Temperature']= 50
df


#multiple dataframe update using multiple condition

df.loc[df['Windspeed']>3 ,['event']]='Sunny'
df
df.loc[df['Windspeed']==3,['event']]='Cloudy'
df